<?php
$return = $this->return;
?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DroidCare Reset Password</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="page-header">
        <h1>DroidCare <small>Reset Password</small></h1>
    </div>
    <?php
    if ($return['status'] === 0) {
        // success
    ?><div class="alert alert-success" role="alert"><?php echo $return['message'][0]; ?></div>
    <?php

    } else {
        // error
    ?><div class="alert alert-danger" role="alert"><?php
        foreach($return['message'] as $message) {
            echo $message; echo "<br>";
        }
    ?></div>
    <?php
    }
    ?>
    <footer>
        &copy; <?php echo date("Y"); ?> DroidCare
    </footer>
</div>

    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>-->
</body>
</html>